export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const UPDATE_APPOINTMENTS = 'UPDATE_APPOINTMENTS';
export const REMOVE_PATIENT_APPOINTMENTS = 'REMOVE_PATIENT_APPOINTMENTS';