export const CREATE_DIAGNOSIS = 'CREATE_DIAGNOSIS';
export const REMOVE_DIAGNOSIS = 'REMOVE_DIAGNOSIS';
export const GET_DIAGNOSES = 'GET_DIAGNOSES';
export const UPDATE_DIAGNOSIS = 'UPDATE_DIAGNOSIS';